### ISSUE TITLE
invalid syntax in settings.py

### ISSUE THREAD

**Issue by ghost** [balena-io/balena-sdk-python#36]
I'm new to using the resin-sdk-python. I'm using python 2.7.11 and when I try to import the resin sdk, I get a syntax error:
`
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/resin/__init__.py", line 9, in <module>
    from .base_request import BaseRequest
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/resin/base_request.py", line 9, in <module>
    from .settings import Settings
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/resin/settings.py", line 56
    print(Message.INVALID_SETTINGS.format(path=config_file_path), file=sys.stderr)
`

but if I change the file to:

`
 sys.stderr.write(Message.INVALID_SETTINGS.format(path=config_file_path))
`
then I don't get an invalid syntax.

Am I using the sdk wrong? or am I using it wrong?

**Comment by EyePulp** [comment]
Yeah, looks like it's in commit 38156a6d3d086a0d8a6151fce0118dc68e7570f9   -- we're getting it too.

**Comment by nghiant2710** [comment]
@freddystban @EyePulp thanks for your report. This is our error since print to stderr using `file=sys.stderr` is not supported by python 2.x. Will have a fix for this soon
